import type { Metadata } from "next";
import { Inter, Epilogue, Poppins } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";

const inter = Inter({ subsets: ["latin"] });
const epilogue = Epilogue({ subsets: ["latin"], variable: "--font-epilogue" });
const poppins = Poppins({
  subsets: ["latin"],
  weight: "900",
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${epilogue.variable} ${poppins.variable}`}>
      <StoreProvider>
        
        <body className={epilogue.className}>{children}</body>
      </StoreProvider>
    </html>
  );
}
